apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  capacity:
    storage: 5Gi  # Capacité de stockage
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard-new
  hostPath:
    path: /data/db  # Le chemin sur le nœud hôte (peut être remplacé par un autre type de stockage, comme NFS)
